name: POSTMAN TEST CASES

on: [push]

jobs:
  runs-on: ubuntu-latest

   steps:
    - name: checkout repository
      uses: actions/checkout@v4

    - name: setup nodejs
      uses: actions/setup-node@v4
      with:
       node-version: '18'

    - name: install newman
      run: npm install -g newman

    - name : run postman test
      run : newman run postman_test/Books.postman_collection.json -e postman_test/test.postman-environment.json

      
      
